name: "PHPStan"

on:
  - push
  - pull_request

env:
  SYMFONY_PHPUNIT_VERSION: ""

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "8.3"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: highest

      - name: "Initialize PHPUnit sources"
        run: "vendor/bin/simple-phpunit --filter NO_TEST_JUST_AUTOLOAD_THANKS"

      - name: "Run PHPStan"
        run: "composer phpstan"
